# Generated by Django 4.2.5 on 2023-09-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="stageone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_name", models.CharField(max_length=200)),
                ("current_day", models.CharField(max_length=200)),
                ("track", models.CharField(max_length=200)),
                ("github_file_url", models.CharField(max_length=200)),
                ("github_repo_url", models.CharField(max_length=200)),
            ],
        ),
    ]
