# Generated by Django 4.2.5 on 2023-09-11 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("endpoint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageone",
            name="status_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stageone",
            name="utc_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="stageone",
            name="github_file_url",
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stageone",
            name="github_repo_url",
            field=models.URLField(max_length=100),
        ),
    ]
